#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : swerv_soc.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Nov 02 22:39:04 +0800 2023
# SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: swerv_soc.sh [-help]
# usage: swerv_soc.sh [-lib_map_path]
# usage: swerv_soc.sh [-noclean_files]
# usage: swerv_soc.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'swerv_soc.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xpm xil_defaultlib axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_22 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_20 fifo_generator_v13_2_5 axi_data_fifo_v2_1_19 axi_crossbar_v2_1_21 axi_protocol_converter_v2_1_20 axi_clock_converter_v2_1_19 blk_mem_gen_v8_4_4 axi_dwidth_converter_v2_1_20)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "swerv_soc.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/736f/gpio_top.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/736f/wb_gpio_wrapper.v" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_wb_gpio_wrapper_0_0/sim/swerv_soc_wb_gpio_wrapper_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lib/beh_lib.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/dbg/dbg.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/swerv_types.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/dec/dec.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/dec/dec_decode_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/dec/dec_gpr_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/dec/dec_ib_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/dec/dec_tlu_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/dec/dec_trigger.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/dma/dma_ctrl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/exu/exu.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/exu/exu_alu_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/exu/exu_div_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/exu/exu_mul_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/ifu/ifu.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/ifu/ifu_aln_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/ifu/ifu_bp_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/ifu/ifu_compress_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/ifu/ifu_ic_mem.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/ifu/ifu_ifc_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/ifu/ifu_mem_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu_addrcheck.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu_bus_buffer.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu_bus_intf.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu_clkdomain.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu_dccm_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu_dccm_mem.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu_ecc.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu_lsc_ctl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu_stbuf.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lsu/lsu_trigger.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/mem.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/lib/mem_lib.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/pic/pic_ctrl.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/swerv.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/swerv_wrapper_dmi.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src/swerv_wrapper_verilog.v" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_swerv_wrapper_verilog_0_0/sim/swerv_soc_swerv_wrapper_verilog_0_0.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi2wb.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi_intercon_wr.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/wb_intercon.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/wb_mux.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/cf_math_pkg.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/addr_decode.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi_pkg.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi_atop_filter.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi_demux.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi_err_slv.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi_id_prepend.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi_intercon.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi_mux.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi_xbar.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/counter.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/delta_counter.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/fifo_v3.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/lzc.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/rr_arb_tree.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/spill_register.sv" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/stream_register.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/9426/axi2wb_intcon_wrapper.v" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_axi2wb_intcon_wrapper_0_0/sim/swerv_soc_axi2wb_intcon_wrapper_0_0.v" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_bootrom_wrapper_0_0/sim/swerv_soc_bootrom_wrapper_0_0.v" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_syscon_wrapper_0_0/sim/swerv_soc_syscon_wrapper_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_22 $vhdlan_opts \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/f71e/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_axi_gpio_0_0/sim/swerv_soc_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_wb_uart_wrapper_0_0/sim/swerv_soc_wb_uart_wrapper_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/72d4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/60de/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/6b0d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_xbar_0/sim/swerv_soc_xbar_0.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/3248/hdl/PWM_Controller_Int.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/3248/hdl/PWM_w_Int_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/3248/hdl/PWM_w_Int_v1_0.v" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_PWM_w_Int_0_1/sim/swerv_soc_PWM_w_Int_0_1.v" \
    "$ref_dir/../../../bd/swerv_soc/sim/swerv_soc.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/c553/hdl/SenSegController.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/c553/hdl/Sen_Seg_Display_v5_0_S00_AXI.v" \
    "$ref_dir/../../../bd/swerv_soc/ipshared/c553/hdl/Sen_Seg_Display_v5_0.v" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_Sen_Seg_Display_0_2/sim/swerv_soc_Sen_Seg_Display_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/c4a6/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9e81/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/d394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../bd/swerv_soc/ipshared/9426" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/736f" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/64dd/src" +incdir+"$ref_dir/../../../../lab1.srcs/sources_1/bd/swerv_soc/ipshared/9426" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_auto_ds_0/sim/swerv_soc_auto_ds_0.v" \
    "$ref_dir/../../../bd/swerv_soc/ip/swerv_soc_auto_pc_0/sim/swerv_soc_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.swerv_soc xil_defaultlib.glbl -o swerv_soc_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./swerv_soc_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./swerv_soc.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key swerv_soc_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc swerv_soc_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./swerv_soc.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: swerv_soc.sh [-help]\n\
Usage: swerv_soc.sh [-lib_map_path]\n\
Usage: swerv_soc.sh [-reset_run]\n\
Usage: swerv_soc.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
