# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/destop/vivado/rtl_src/liteDRAM.xdc

# XDC: D:/destop/vivado/rtl_src/rvfpga.xdc

# Block Designs: bd/swerv_soc/swerv_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc || ORIG_REF_NAME==swerv_soc} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_axi2wb_intcon_wrapper_0_0/swerv_soc_axi2wb_intcon_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_axi2wb_intcon_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_axi2wb_intcon_wrapper_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_swerv_wrapper_verilog_0_0/swerv_soc_swerv_wrapper_verilog_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_swerv_wrapper_verilog_0_0 || ORIG_REF_NAME==swerv_soc_swerv_wrapper_verilog_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_wb_gpio_wrapper_0_0/swerv_soc_wb_gpio_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_wb_gpio_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_wb_gpio_wrapper_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_syscon_wrapper_0_0/swerv_soc_syscon_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_syscon_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_syscon_wrapper_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_bootrom_wrapper_0_0/swerv_soc_bootrom_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_bootrom_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_bootrom_wrapper_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_axi_interconnect_0_0/swerv_soc_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_axi_interconnect_0_0 || ORIG_REF_NAME==swerv_soc_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_axi_gpio_0_0/swerv_soc_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_axi_gpio_0_0 || ORIG_REF_NAME==swerv_soc_axi_gpio_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_wb_uart_wrapper_0_0/swerv_soc_wb_uart_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_wb_uart_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_wb_uart_wrapper_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_xbar_0/swerv_soc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_xbar_0 || ORIG_REF_NAME==swerv_soc_xbar_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_PWM_w_Int_0_0/swerv_soc_PWM_w_Int_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_PWM_w_Int_0_0 || ORIG_REF_NAME==swerv_soc_PWM_w_Int_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_ptc_wrapper_0_0/swerv_soc_ptc_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_ptc_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_ptc_wrapper_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_xlconcat_0_0/swerv_soc_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_xlconcat_0_0 || ORIG_REF_NAME==swerv_soc_xlconcat_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_wb_spi_wrapper_0_0/swerv_soc_wb_spi_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_wb_spi_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_wb_spi_wrapper_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_axi_iic_0_0/swerv_soc_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_axi_iic_0_0 || ORIG_REF_NAME==swerv_soc_axi_iic_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_My_PWM_0_0/swerv_soc_My_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_My_PWM_0_0 || ORIG_REF_NAME==swerv_soc_My_PWM_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_auto_ds_0/swerv_soc_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_auto_ds_0 || ORIG_REF_NAME==swerv_soc_auto_ds_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_auto_pc_0/swerv_soc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swerv_soc_auto_pc_0 || ORIG_REF_NAME==swerv_soc_auto_pc_0} -quiet] -quiet

# XDC: bd/swerv_soc/swerv_soc_ooc.xdc
